### ISSUE TITLE
Can we increment the package version?

### ISSUE THREAD

**Issue by furgalep** [catkin/catkin_simple#21]
We have a big team and I'm always in search of new ways to make our software report good error messages that help (even novice) team members solve the problem for themselves. This was the motivation behind the ALL_DEPS_REQUIRED option. However, with an old version of catkin_simple, this option is simply ignored. 

Now, it would be great if we could increment the package version so that I can write my package.xml files to require a minimum version of catkin_simple that supports this option. Then people would get one message to upgrade catkin_simple then (after upgrade) another message that they have a missing package.

Possible?

**Comment by NikolausDemmel** [comment]
I think we can close this as superseeded by https://github.com/catkin/catkin_simple/issues/29
