### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by lokijota** [catkin/catkin_simple#33]
I'm a total newbie to this, sorry for the question, but how do I install/configure this?

**Comment by wjwwood** [comment]
It's a catkin package, so you can just do the normal CMake process of `mkdir build; cd build; cmake ..; make`, or you can put it in a workspace with other catkin packages and use a tool to build all of them.

This isn't officially supported or documented, so there will be some assembly required.

**Comment by wjwwood** [comment]
I'm going to close this, but you can continue to discuss it if you like. I can reopen it later if necessary. You might also consider asking questions like these on http://answers.ros.org/questions/.
